### ISSUE TITLE
Just a personal issue

### ISSUE THREAD

**Issue by theStoryEngine** [lathoub/three.cs#1]
The readme says it runs right out of the box, but visual studio tells me that it's a library and it needs an executable output in order to run. Which I could figure out, but it says it should run right out of the box. Also which .net framework did you use? because I get 81 warnings (and 14 errors when I try to build)

**Comment by lathoub** [comment]
Added missing resources and bumped to .Net 4.5.2 using Visual Studio 2015
(I have 99 personal issues, but this ain't one :-))
