### ISSUE TITLE
hello lathoub

### ISSUE THREAD

**Issue by elkhalafy** [lathoub/three.cs#2]
Hello latgoub

Thanks you for support there.js for .Net .. i hope keep development this project and I wish support new features of there.js in there.cs and please add The DLL library for .Net 4.5 

I need your help for important .. I need your email please . You only one can help me and so it 

Please add contact information for you 

Thanks

**Comment by elkhalafy** [comment]
you are here

**Comment by elkhalafy** [comment]
Port SculptGL Please for C# on .NET Platform please

**Comment by lathoub** [comment]
The port from three.js to c# is not automatic, and took me a lot of time. I created the c# to learn the internals of three.js and the use of JavaScript with WebGL.
I do not plan to port SculptGL to c# (with all respect, i find your question somewhat strange - a lot of effort go into a port, its not something that can be done in 15 minutes)

**Comment by elkhalafy** [comment]
Brother Lathoub, Thank you for your answer me

first of All, what is the strange of my question !!? you can't do it !!!, You can brother. because you know JS and C#, anyways, I don't know you ported Three.js into C# for learning, anyway, your opinion must respect, I'm just asked you, if you have free time to do that, it will be great for this project to port it into C# and .NET Platform ( poor platform ) as SDK or DLL Library, I said you ported Huge project like Three.js, so you can port that project for .NET..
anyway, sorry, and I hope accept my apology, have a nice day 


Muhammad - EG.
